[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
board_dir = boards
framework = arduino

; --- OTTIMIZZAZIONE MEMORIA FONDAMENTALE PER ESP32-S3 RGB ---
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi ; Forza la PSRAM a 80MHz Octal Bus
board_upload.flash_size = 16MB

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -O2 ; Ottimizzazione del compilatore per massima velocità
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_SUPPRESS_DEFINE_CHECK
    -DBOARD_HAS_PSRAM
    -DLV_USE_ROLLER=1 ; Risolve l'errore del roller senza toccare lv_conf.h
    -DCORE_DEBUG_LEVEL=0 ; Disabilita log seriali pesanti nel loop
    -I./src

monitor_speed = 115200
upload_port = COM6

lib_deps =
    lovyan03/LovyanGFX
    lvgl/lvgl@^8.3.11
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    ESPAsyncWebServer-esphome